"""Initial migrations

Revision ID: 77628c65e761
Revises: 
Create Date: 2024-10-02 22:23:24.519213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77628c65e761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('refresh_token', sa.String(length=100), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('moving_time', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Integer(), nullable=False),
    sa.Column('total_elevation_gain', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('user')
    # ### end Alembic commands ###
